// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJV0KyBQhu3DfU6Mu5GJwtxCdlCvNSfvU',
    appId: '1:668648782684:web:aeeb42eb657913d4e61f99',
    messagingSenderId: '668648782684',
    projectId: 'tennis-court-84530',
    authDomain: 'tennis-court-84530.firebaseapp.com',
    storageBucket: 'tennis-court-84530.firebasestorage.app',
    measurementId: 'G-LTB0PEYD8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYOb8x_yEMPcVb2oux1JG1PVxQKleJLPo',
    appId: '1:668648782684:android:be4eeca847f21283e61f99',
    messagingSenderId: '668648782684',
    projectId: 'tennis-court-84530',
    storageBucket: 'tennis-court-84530.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRDEudvEuySXr9HuZopE0EaSHaTBY_UVA',
    appId: '1:668648782684:ios:19d2740f45742105e61f99',
    messagingSenderId: '668648782684',
    projectId: 'tennis-court-84530',
    storageBucket: 'tennis-court-84530.firebasestorage.app',
    iosBundleId: 'com.example.tennisCourtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRDEudvEuySXr9HuZopE0EaSHaTBY_UVA',
    appId: '1:668648782684:ios:19d2740f45742105e61f99',
    messagingSenderId: '668648782684',
    projectId: 'tennis-court-84530',
    storageBucket: 'tennis-court-84530.firebasestorage.app',
    iosBundleId: 'com.example.tennisCourtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJV0KyBQhu3DfU6Mu5GJwtxCdlCvNSfvU',
    appId: '1:668648782684:web:b93981259bf4be73e61f99',
    messagingSenderId: '668648782684',
    projectId: 'tennis-court-84530',
    authDomain: 'tennis-court-84530.firebaseapp.com',
    storageBucket: 'tennis-court-84530.firebasestorage.app',
    measurementId: 'G-7D52CFSPEQ',
  );
}
